### ISSUE TITLE
Eliom distillery: need to forbid some project name due to generated filename?

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#102]
When creating a new project with eliom-distillery, Makefile.%%PROJECT_NAME%% is created for example. There is also Makefile.options by default.

But we can use
```
eliom-distillery -name options -template os.pgocaml
```
to create a project. We have the warning the Makefile.options file exists but we can say yes to replace the file (and of course, the final project it's not working).

Shoud it be forbidden to create a project named *options*?
Or does the filename need to be changed to avoid conflicts?

**Comment by vasilisp** [comment]
> Shoud it be forbidden to create a project named options?
> Or does the filename need to be changed to avoid conflicts?

I would prefer the first, because it would be complicated to conditionally rename `Makefile.options` and include the correct file from `Makefile`. A PR would be appreciated :).

**Comment by dannywillems** [comment]
@vasilisp See https://github.com/ocsigen/eliom/pull/369.

**Comment by vasilisp** [comment]
Fixed, thanks @dannywillems .
