### ISSUE TITLE
Default template : compiling problem with pg_ctl

### ISSUE THREAD

**Issue by tobiasBora** [ocsigen/ocsigen-start#15]
Hello,

The default template is buggy: when I try to compile it (with make test.byte), I get the error
```
Makefile.local:53: *** "no 'pg_ctl' binary found, please run 'scripts/find_pg_ctl.sh'".
Arrêt.
```
I tried to run this script but I got three problems:
- The first one, very easy to solve I think is just that the script isn't executable

- The second one, easy to solve too, occured when I run it like this: "scripts/find_pg_ctl.sh", I have this error:
```
scripts/find_pg_ctl.sh: 15: scripts/find_pg_ctl.sh: function: not found
scripts/find_pg_ctl.sh: 17: scripts/find_pg_ctl.sh: Syntax error: "}" unexpected
```
To avoid this problem I run instead
```
bash scripts/find_pg_ctl.sh
```
(I think a simple bang redefinition should solve the problem)

- The last one is that even when I run it with bash I get a problem in the file created: cat pg_ctl gives me:
```
Error : two many symbolic links
```

Thank you,

Tobias.

PS: I don't really know Postgresql, but I'm not sure that using pg_ctl is a solution, I think there is a good reason why this function isn't in the path for debian and ubuntu no ? I found some links about pg_createcluster, which is in the path to change the default path of the database, and
```
pg_ctlcluster <version> <cluster> start
```
to lanch a specific cluster

**Comment by dannywillems** [comment]
@balat @vasilisp This script doesn't exist anymore. I think we could close this issue.
