### ISSUE TITLE
Installation failed because of `text`.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#162]
When we copy-paste the installation commands, it fails when installing the dependency `text` (due to `camlp4`?). We need to run again the command `opam install ocsigen-start`.
Could `text` be updated in official opam repository? I post here because I remember @vasilisp said something about it when I updated the installation commands (see #108).

**Comment by dannywillems** [comment]
Here the error:
```
# I: Testing whether -liconv is needed
# ocamlfind: Package `camlp4.quotations.o' not found
# W: Field 'pkg_camlp4_quotations_o' is not set: Command ''/tmp/os/_opam/bin/ocamlfind' query -format %d camlp4.quotations.o > '/tmp/oasis-65f237.txt'' terminated with error code 2
# E: Cannot find findlib package camlp4.quotations.o
# E: Failure("1 configuration error")
```

**Comment by vasilisp** [comment]
Yes, we can do a PR against https://github.com/ocaml/opam-repository declaring the dependency. In fact, the dependency can be optional if we also patch the build system. See vbmithr/ocaml-text#3 .

For a smooth installation with the current state of things, it suffices to explicitly install `camlp4` before.

**Comment by dannywillems** [comment]
@vasilisp You think it suffices to add `camlp4` in `depends` section in the `opam` file [here](https://github.com/ocaml/opam-repository/blob/master/packages/text/text.0.8.0/opam)? If yes, I do it.

**Comment by vasilisp** [comment]
I think that suffices, yes.

**Comment by dannywillems** [comment]
https://github.com/ocaml/opam-repository/pull/7520 has been merged and it seems working.
