### ISSUE TITLE
Fix CI (DONE for master, TODO for PRs)

### ISSUE THREAD

**Issue by Drup** [ocsigen/ocsigen-start#165]
CI is not here to be ignored. If it fails, fix it. I'm a bit tired of being spammed by it.

**Comment by dannywillems** [comment]
I agree it's annoying to receive these error build mails.

**Comment by dannywillems** [comment]
Why is Travis not used for CI?

**Comment by dannywillems** [comment]
@Drup It seems it's during the documentation generation. I resolved two problems but I have the following error:
```
ODOC_WIKI_SUBPROJECT="client" \
    eliomdoc -client \
    -ppx -package yojson,calendar,ocsigen-widgets.client \
     -intro doc/indexdoc.client -colorize-code -stars -sort \
     -i  -g odoc_wiki.cma \
     -d doc/client/wiki \
     -I _client/src/ \
     src/os_tips.eliomi src/os_uploader.eliomi src/os_tools.eliomi src/os_handlers.eliomi \
     src/os_date.eliomi src/os_push_notifications.eliomi src/os_userbox.eliomi \
     src/os_services.eliomi
     src/os_email.eliomi src/os_comet.eliomi src/os_notif.eliomi src/os_lib.eliomi \
     src/os_user_proxy.eliomi src/os_session.eliomi src/os_current_user.eliomi src/os_page.eliomi \
     src/os_user.eliomi src/os_msg.eliomi src/os_request_cache.eliomi src/os_view.eliomi

Fatal error: exception Failure("Unknown extension for file odoc_wiki.cma.")
Makefile:240: recipe for target 'doc' failed
```
Is it a problem with wikidoc?

**Comment by Drup** [comment]
Ca c'est un soucis : `-i  -g odoc_wiki.cma` 
`-i` attend lui même un argument (l'endroit ou aller chercher `odoc_wiki.cma`).

**Comment by Drup** [comment]
You can find that location with something like `$(ocamlfind query wikidoc)`.

**Comment by dannywillems** [comment]
@Drup #209 must be OK.

**Comment by dannywillems** [comment]
🎉 🎉  Fixed! 🎉 🎉

**Comment by dannywillems** [comment]
But I think we need to see what's happening with PR. @vasilisp

**Comment by vasilisp** [comment]
Yes, let's keep the issue open until we fix the PRs.

**Comment by dannywillems** [comment]
@vasilisp Maybe add in the title "for PR" to be more explicit?

**Comment by vasilisp** [comment]
For the PRs, I have initiated a rebuild of the docker container. We will see.

**Comment by dannywillems** [comment]
@vasilisp Could be interesting to test the template in Jenkins no?

**Comment by vasilisp** [comment]
@dannywillems sure :). At the very least, we should be able to compile it. Ensuring that the server can launch would be a bit harder but also useful.

**Comment by dannywillems** [comment]
@vasilisp PostgreSQL is installed on the docker container or do we need to add it in `.jenkins.sh`?

**Comment by dannywillems** [comment]
@vasilisp --> http://stackoverflow.com/questions/18621134/what-does-fatal-error-computing-merge-base-mean?

**Comment by dannywillems** [comment]
@vasilisp @Drup CI Broken :(. Due to `text` and `conf-gmp`.
https://ci.inria.fr/ocsigen/job/Ocsigen-start-4.02/266/console
https://ci.inria.fr/ocsigen/job/Ocsigen-start-4.02/268/console

**Comment by dannywillems** [comment]
Now it's fixed...

**Comment by dannywillems** [comment]
After discussing with @balat, Travis will be added to ocsigen-start (like lwt does). It's also working with PR and doesn't require a lot of configurations.
Of course, Jenkins will stay (for updating documentation).
