### ISSUE TITLE
widget and toolkit 

### ISSUE THREAD

**Issue by Drup** [ocsigen/ocsigen-start#198]
Today, I installed ocsigen-start for the first time (yes, I know ...). I was surprised to find that ocsigen-toolkit *and* ocsigen-widgets were both dependencies. 

Wasn't toolkit supposed to replace widget ?
Can we *finally* kill it and stop making the user's life even more complicated and confusing ?

**Comment by dannywillems** [comment]
@Drup It's in progress. It remains only one depencendy which is in `Os_userbox` about button. Toolkit will replace widget.

**Comment by Drup** [comment]
@dannywillems Ok, good to hear!

**Comment by dannywillems** [comment]
@Drup Fixed by #221. I close.

**Comment by Drup** [comment]
Yay. We should fix the description of ocsigen-widget so that it's obvious it's deprecated and put a link to ocsigen-toolkit.

**Comment by dannywillems** [comment]
It's already done in ocsigen-widgets.

**Comment by dannywillems** [comment]
Not the link. I do it.
