### ISSUE TITLE
Remove dependency to the binding to ImageMagick.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#231]
@vouillon suggests to remove the dependency to the binding to ImageMagick which is only used in one function (`Os_uploader.crop_image`). Instead of using the binding, the binaries can be called directly.

**Comment by vasilisp** [comment]
That would be awesome, especially if ImageMagick becomes optional (i.e., if no binary, just fail gracefully in uploading an avatar).

**Comment by dannywillems** [comment]
@vasilisp Any idea to make optional ImageMagick (so without binary)? Do we need to implement the functions?

**Comment by vasilisp** [comment]
The service that uses ImageMagick can just fail (if we can't find the binary) and leave the user without an avatar. I would personally love to eliminate ImageMagick from my development setups :).

**Comment by dannywillems** [comment]
Oh I misunderstood what you meant in your last message. I thought you wanted to remove also the dependency about the ImageMagick binary.

**Comment by dannywillems** [comment]
By the way, il will remove the warning:
```
Warning 58: no cmx file was found in path for module Magick, and its interface was not compiled with -opaque
```
