### ISSUE TITLE
Problem with ocsigen-widgets

### ISSUE THREAD

**Issue by fellz** [ocsigen/ocsigen-start#24]
make
Makefile:179: .depend: No such file or directory
eliomdep -server -package pgocaml,pgocaml.syntax,text,macaque.syntax,calendar,safepass,ocsigen-widgets.server,magick -eliom-inc src/ src/eba_email.eliomi > _deps/src/eba_email.eliomi.server
Fatal error: exception Fl_package_base.No_such_package("ocsigen-widgets.server", "")
make: *** [_deps/src/eba_email.eliomi.server] Error 2

and

opam install ocsigen-widgets.server
[ERROR] No package named ocsigen-widgets found.

opam install ocsigen-widgets
[ERROR] No package named ocsigen-widgets found.

**Comment by unhammer** [comment]
fellz commented on 12 Nov 2014:
> @balat btw is there any way to recompile project automatically and restart web server after i save the file with code ( with some changes)?

On Linux, you can install inotify-tools and do

     $ make test.opt & pid=$!; while inotifywait -e close_write *.eliom ; do kill $pid; make test.opt & pid=$!; done                                                                           

(just note that if you Ctrl-C that loop, you'll have to `kill $pid` or `exit` the terminal to shut down the last server)

**Comment by bruce-ricard** [comment]
@vbmithr the `opam-ocsigen` repo appears to not exist anymore. I'm running into the same error when running in an Ubuntu Docker container. Is there another workaround please?

**Comment by bruce-ricard** [comment]
`opam install dbm` fixed the issue for me. It's unfortunate that we don't get a compilation error, but only a runtime one...
