### ISSUE TITLE
Add an error message when SASS is not available.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#247]

**Comment by pwbs** [comment]
error or warning?

**Comment by dannywillems** [comment]
@pwbs error because the template won't compile. The value `USE_SASS` in `Makefile.style` must be changed. By default, SASS is activated.
Maybe change automatically the value of `USE_SASS` depending on the `sass` binary.

**Comment by pwbs** [comment]
Ok I guess it makes sense :)

**Comment by dannywillems** [comment]
See #256
