### ISSUE TITLE
find_pg_ctl.sh: hint the user about updatedb if no pg_ctl is found

### ISSUE THREAD

**Issue by Armael** [ocsigen/ocsigen-start#27]
If the user has just installed postgresql, the locate's db may not be up to date. If the script does not found pg_ctl, saying to the user "maybe you should run 'updatedb' as root" may be helpful.

**Comment by balat** [comment]
We must find a better way to create the db, without relying on that ugly script.
May be look for pg_ctl in PATH and at its usual psoition for Debian?
Or use something else? What is the recommended way (for Debian? for others?)

**Comment by balat** [comment]
Debian recommends to use pg_ctlcluster instead. Should we use this instead of pg_ctl?
@vasilisp could you have a look at this (may be with the intern)?

**Comment by vasilisp** [comment]
Sure, we can look at this.

`pg_ctlcluster` seems to be a Debian-specific wrapper around `pg_ctl` (no clue what the added value is). So we still need to support `pg_ctl` for everything other than Debian and Ubuntu.

For another data point, FreeBSD just puts `pg_ctl` in the `$PATH`. No clue about anything else :).

**Comment by dannywillems** [comment]
@vasilisp @balat PR #123 fixed the issue with `pg_ctlcluster`. The script `find_pgctl.sh` has been removed because all it's done in `Makfile.db`.

But nothing has been done for the update. Do we add something (as suggested by @Armael)?
