### ISSUE TITLE
find_pg_ctl.sh: do not depend on the directory the script is called from

### ISSUE THREAD

**Issue by Armael** [ocsigen/ocsigen-start#28]
I saw someone do "cd scripts; ./find_pg_ctl.sh" instead of "scripts/find_pg_ctl.sh" to launch the script (+ the autocompletion can be weird and do not work as first if you start with a directory, which can be confusing). Which didn't worked, the pg_ctl link being in the scripts/ subdirectory.

Maybe some sh magic could prevent this?

**Comment by balat** [comment]
You're right. But actually this script is ugly and should be removed completely in favor of a better solution ...

**Comment by dannywillems** [comment]
@balat @vasilisp I think we could close this issue no? This scripts doesn't anymore exist.
