### ISSUE TITLE
Forgot password links

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#285]
It seems forgot password links are broken ( @balat, @pwbs).

**Comment by balat** [comment]
@pwbs

**Comment by dannywillems** [comment]
@pwbs ?

**Comment by pwbs** [comment]
The current state: the form is an HTML form with a service as a HTML form action: when it's submitted, the server doesn't tell the client to do anything.

What we want: 
1. display a message about the action 
2. close the forgot-password form

Well, I don't know how to do this with an HTML form action, I don't even know if it's technically possible (with the current state of everything but mostly Eliom).

The easy solution I see is to change that HTML form action into an RPC.

**Comment by pwbs** [comment]
Related to https://github.com/ocsigen/ocsigen-start/issues/342
