### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by agarwal** [ocsigen/ocsigen-start#301]
```
$ make
...
eliomc -c -package pgocaml -package pgocaml.syntax -package macaque.syntax -package calendar -package safepass -I _server/src/ -g src/os_db.ml
File "src/os_db.ml", line 230, characters 39-55:
Error: Unbound module Os_types
make: *** [_server/src/os_db.cmo] Error 2
```

**Comment by dannywillems** [comment]
Maybe related #175.

**Comment by agarwal** [comment]
> Maybe related to #175.

Note I'm not using `-j`. I get the same error explicitly setting to `1`:

```
$ make -j1
eliomc -c -package pgocaml -package pgocaml.syntax -package macaque.syntax -package calendar -package safepass -I _server/src/ -g src/os_db.ml
File "src/os_db.ml", line 230, characters 39-55:
Error: Unbound module Os_types
make: *** [_server/src/os_db.cmo] Error 2
```

**Comment by vasilisp** [comment]
Maybe something is wrong with the `.depend` files? Can you look if there is a stated dependency from `Os_db` to `Os_types` there? Does `make distclean` and then `make` improve things?

**Comment by agarwal** [comment]
A `make distclean` resolved the problem. At first, I didn't have necessary dependencies installed, so I guess something got messed up in the incremental calls to `make`.
