### ISSUE TITLE
Add demo for ot_spinner

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#316]

**Comment by vasilisp** [comment]
Should I do it? Assign it to someone!

**Comment by vasilisp** [comment]
See #327 .

**Comment by dannywillems** [comment]
@vasilisp I suppose #327 fix this but I don't know what we must see with the demo. Could you explain? I only see the scrollbar moving.

**Comment by vasilisp** [comment]
The DOM gets updated when the node is ready, doesn't it? The appearance is a matter of CSS (I think), and I haven't investigated it.

**Comment by dannywillems** [comment]
@vasilisp Yes it is: we have a message saying the page was generated. But we don't know what happened.

**Comment by balat** [comment]
I fixed the style in OT.
