### ISSUE TITLE
Set opam depexts

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#320]
posgresql, sass or sassc
Anything else?

Also check that it is done for Server and Eliom, etc.

**Comment by dannywillems** [comment]
@balat See #323 for sass and PostgreSQL.

**Comment by dannywillems** [comment]
@balat I don't know if packages for mobile applications must be added in OPAM depext. Some people can use ocsigen-start without mobile application.

**Comment by balat** [comment]
Thank you :)
Do we have other dependencies? postcss?
Is it possible to say something like sassc if available, sass otherwise?

About mobile apps: Indeed. I don't know. We won't ask to install all the android stuff anyway ;)

**Comment by dannywillems** [comment]
@balat postcss must be installed with NPM I think. And it is not mandatory. A warning is printed if postcss is not installed.
I don't know if there are other dependencies.

About `sassc`, I don't know how to install on Ubuntu/Debian/Mac OSX. And I don't know if we can use condition in OPAM.

**Comment by vasilisp** [comment]
`postcss` doesn't exist in Debian/Ubuntu. I don't have it installed, and I haven't noticed any problems :).

I don't think there is a way to express disjunctive depexts (`sass | sassc`). Pick the one you like best, depexts are more like recommendations than like hard constraints.

For Eliom and the server we should be OK (our dependencies have depexts, and it is their business to declare them).

**Comment by balat** [comment]
Ok thanks.

sassc is much faster than sass, but it is only present in very recent distribution :/
That's why I don't know. Perhaps it's safer to stick with sass for now.

**Comment by Drup** [comment]
> I don't think there is a way to express disjunctive depexts (sass | sassc).

Add `conf-sass` packages in the opam repository and have OR dependencies on that. ;)

**Comment by dannywillems** [comment]
@balat Could we close it? Everything is installed I think (except NPM)
