### ISSUE TITLE
Check instructions for building an iOS app

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#322]

**Comment by balat** [comment]
@pwbs :-)

**Comment by dannywillems** [comment]
Is it done? @pwbs @balat

**Comment by pwbs** [comment]
I don't know... I managed to build the app for os-demo, so I'd guess that it's alright now... XD

**Comment by dannywillems** [comment]
@pwbs And you followed the instructions given in the README?

**Comment by pwbs** [comment]
I did this: 

```
make ios
```

**Comment by pwbs** [comment]
I don't know if there's some place where we tell people to install cordova and cordova plugins...

**Comment by dannywillems** [comment]
I think there is nothing more specific for building than changing `android`to `ios` : other issues come generally from Apple configuration. So I close.

**Comment by pwbs** [comment]
yeah if instructions are fine for android, it should be fine for iOS too, except if someone did something bad on purpose for iOS... XD

**Comment by dannywillems** [comment]
@pwbs It is installed locally since #411 if it's not installed.
