### ISSUE TITLE
Reference manual

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#324]
I think the current version is almost enough.

But:

- [ ] There is an unfinished sentence in Databse section. @vasilisp what did you want to say?
- [ ] We need a short description of the features of the library, that links to the corresponding API doc.

**Comment by dannywillems** [comment]
@balat Maybe use this issue #230?

**Comment by vasilisp** [comment]
For the unfinished sentence, I don't remember what I wanted to say. Maybe I wanted to say that the database can be extended with new tables for the users' needs? I will look into it tomorrow.
