### ISSUE TITLE
Change avatar in settings.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#326]
- The avatar is not resized.
- Style not done.

**Comment by dannywillems** [comment]
@balat I think we can remove the binding to imagemagick at the same time (see #231) with the solution you use in bs.

**Comment by balat** [comment]
@sagotch ?

**Comment by dannywillems** [comment]
@sagotch realized it's just a CSS issue for resizing. About cropping the image server-side, we can use:
```
Lwt_process.exec
  ("", [|"convert"; "+repage" ;
         "-strip"; "-interlace"; "Plane"; "-auto-orient";
         "-define"; Printf.sprintf "jpeg:size=%dx%d" (2 * w) (2 * h);
         "-resize"; Printf.sprintf "%dx%d!" w h; "-quality"; "85";
         "-background"; "white"; "-flatten";
            (* In case of transparent image *)
         input_file;
         "jpg:" ^ output_file|])
```
as suggested in https://github.com/ocsigen/ocsigen-start/pull/335.
