### ISSUE TITLE
Demo: example with DB

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#334]
An example of page generated from db, using PGOCaml. For example display the list of users.
Also fix makefiles.

**Comment by dannywillems** [comment]
What do you mean by fixing makefiles? @balat

**Comment by balat** [comment]
I mean that it does not compile :)
The solution is probably to do
```
export DB_HOST
export DB_PORT
etc.
```
and remove ```ENV_PSQL```
(at least we won't see the password in the terminal).
