### ISSUE TITLE
Fix sign-up popup (close popup and display Os_msg)

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#342]

**Comment by vasilisp** [comment]
Eliom bug, I am afraid. I am investigating.

**Comment by vasilisp** [comment]
I have established that it is an issue with Eliom client-side routing. We don't find the right page to load after the action, so the old page with the pop-up stays there. It only seems to happen if we try to sign up while on the home page (i.e., empty path).

**Comment by vasilisp** [comment]
https://github.com/ocsigen/eliom/commit/14c369b1d357409a6373190b7ee75d0b0484cd29 seems to resolve the issue. We were trying to route to the path `./`, and that didn't work. Probably not the most general solution possible.  I am pretty sure we have other similar issues related to URL management that will come up.

**Comment by balat** [comment]
Ok it is better indeed. The popup is now closed.
We must now fix the message.
When the page is generated server-side the message is shown after the page is displayed.
When the page is generated client-side, Os_msg is called too early.
This is a common problem when programming in shared section.
The order of evaluation is not the same :/
I'll try to add a onload somewhere ...

**Comment by balat** [comment]
Actually the onload was already here.
But onload event was done twice: once during the action (which is wrong), and then after displaying the new page ...
https://github.com/ocsigen/eliom/pull/446 fixes this in Eliom
and https://github.com/ocsigen/ocsigen-start/pull/360 in OS
