### ISSUE TITLE
Os_notif: option ~notfor seems not to work

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#373]
`~notfor:Me` sends to noone and `User` to anyone (if I'm right).
May be a bug in Eliom_notif.

**Comment by balat** [comment]
@vasilisp may be you know that piece of code better than me (I have no idea about the identity stuff).

**Comment by vasilisp** [comment]
@balat, I don't know the code that well, but I will take a look. (I don't how much I can do today, but I can spend some time on it on Thursday or Friday.)

**Comment by balat** [comment]
Ok do not miss your plane ;)
If you can't I'll have a look.
