### ISSUE TITLE
eliom-distillery: command not found

### ISSUE THREAD

**Issue by ingoglia** [ocsigen/ocsigen-start#375]
I was able to successfully install ocsigen-start on Debian, however when I attempt to run :

eliom-distillery -name myapp -template os.pgocaml

I receive the response:
bash: eliom-distillery: command not found

**Comment by dannywillems** [comment]
@ingoglia See #374. Which command did you use to install ocsigen-start?
`eliom-distillery` comes with Eliom which is installed with ocsigen-start by using `opam install ocsigen-start`.

**Comment by vasilisp** [comment]
Your `$PATH` doesn't seem up-to-date, so you are probably missing the

```
eval $(opam config env)
```

step suggested in #374. You need to do that to update the environment of all shells after installation and before you log out of your machine. Upon the next login, the environment will get updated automatically by the commands that OPAM added to your `~/.profile` (if you allowed it to do so).

**Comment by ingoglia** [comment]
I didn't realize that you needed to update the path every time after performing the opam switch. I installed again and everything seems to be generating properly. Thank you!
