### ISSUE TITLE
Add language selector in settings page

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#403]

**Comment by sagotch** [comment]
Have a look at this https://github.com/dannywillems/ocsigen-start/commit/defe725dd907768afd4878cd82259c903f22a05c

**Comment by balat** [comment]
@dannywillems is this ready for a PR?

**Comment by dannywillems** [comment]
@balat No it's not. It was just for testing.

**Comment by balat** [comment]
It's now here but currently broken.
