### ISSUE TITLE
Compatibility with 4.02.3.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#413]
ocsigen-i18n needs ocaml >= 4.03.0. I don't know if Ocsigen Start must be compatible with 4.02.3. @balat @sagotch ?

**Comment by dannywillems** [comment]
I saw it was also modified in Ocsigen Start. Sorry. I close.

**Comment by vasilisp** [comment]
I modified the constraints when I noticed that `ocsigen-i18n` needs `>=` 4.03.0. I think we are OK, given that OS is a new project with no legacy apps to support. But in case supporting 4.02.x with `ocsigen-i18n` wouldn't involve much work (@sagotch ?), so much the better.
