### ISSUE TITLE
Last small fixes before 1.0

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#414]
A list of small fixes:

- [x] Stylesheet problems on main page/header @balat
- [x] Language selector broken: language is not set correclty client-side. @vasilisp
- [x] Small screens: impossible to reach disconnection button in drawer (scroll too short) @balat
- [x] Find a better place for description text that works both on mobile/desktop and connected/non-connected @balat
- [x] Account creation: wrong redirection after setting password (non-attached parameters kept in URL)
- [x] Should go to settings page after validating a new e-mail address (how to do that?) @vasilisp #422 
- [x] Fix Os_tips (Os_tips is not working at all with client-side generated pages) @balat
- [x] Wrong mouse cursor on many links ad buttons
- [x] Reload after action does _not_ stay on same page on mobile @vasilisp
- [x] Fix creation of ocsipersist database with capitalized letters @vasilisp ocsigen/eliom#478

**Comment by balat** [comment]
The problem with the language selector is related to a broken action:

```
POST http://localhost:8080/settings?__nl_n_eliom-process.p=true 500 (Internal Server Error)
bone_bd43bad….js:63344 [eliom:request] can't silently redirect a Post request to non application content
bone_bd43bad….js:63344 [eliom] Async: (Failure "can't silently redirect a Post request to non application content")
```

This is a POST form towards an action, registered both sides ...

@vasilisp any idea about this?

**Comment by vasilisp** [comment]
@balat no idea (yet), I am looking into it. I will also look into the other service-related issue (account creation).

**Comment by vasilisp** [comment]
@balat https://github.com/ocsigen/ocsigen-start/commit/6efc71a9e8e35a617113d28a1a64f9fa3d6da772 fixes server-side (not client-side) language selection. The redirection message follows from the action handler failing. Is that the problem you have in mind?

**Comment by balat** [comment]
I cannot reproduce the account creation problem :/
I had it with a fresh project (user 1).

About the language selector:
One problem is that we use Os_handler.update_language instead of PROJECT_NAME_language.update_language. I suggest to remove the lib version and put the handler in the template for now. (I'd like to find a way to put all this in the lib but it depends on the type defined in ..._i18n.eliom. May be a functor could solve this).

But this does not explain the error message with the POST form and the action ...

**Comment by balat** [comment]
Ok I just saw your last message. Probably calling the version in PROJECT_NAME_language.update_language should solve the problem client-side?

**Comment by vasilisp** [comment]
I am about to test. Even that one may need to be wrapped by `Os_session.connected_wrapper`, like in my commit.

**Comment by vasilisp** [comment]
https://github.com/ocsigen/ocsigen-start/commit/831d4cbb7294e82d76dea2b068b38e2a31451a10 does what you suggest. The action works, but the new language needs a browser reload to take effect. Is that expected?

**Comment by sagotch** [comment]
No it is not expected.

Why does the client side handler do not use `PROJECT_NAME_language` module as well? References should be updated and page automatically reloaded.

**Comment by vasilisp** [comment]
There is no client-side implementation in `PROJECT_NAME_language`.

The reload issue is actually more complicated. The first time that I try to change the language after connecting the language doesn't change without a reload, but later the language does change automatically.

**Comment by vasilisp** [comment]
@balat, I can't reproduce the account creation problem either (and I did try with a fresh project).

**Comment by sagotch** [comment]
Oups, I was talking about variables in `PROJECT_NAME_i18n`, not `_language`...

**Comment by balat** [comment]
Indeed. I can't reproduce it either ...

There are many other small bugs to be fixed. Please test everything carefully.

**Comment by vasilisp** [comment]
After a few stupid mistakes on my part @sagotch's suggestion works (#416). There is still a strange thing going on: in the mobile app, setting the language takes us to the home page and I don't understand why.

**Comment by balat** [comment]
Ok so I'll add "reload does not work on mobile app" in the list ;)

**Comment by vasilisp** [comment]
For the last remaining point see #422. But I think we will need to add a few more items to the list.

**Comment by vasilisp** [comment]
@balat changing the language in the mobile app is still broken iff we are under a path (more generally, actions should be broken). Working on it. I think I know what is going on.

**Comment by vasilisp** [comment]
* [1.0.0 tag](https://github.com/ocsigen/ocsigen-start/releases/tag/1.0.0)
* [`opam-repository` pull request](https://github.com/ocaml/opam-repository/pull/8441/files)
