### ISSUE TITLE
Cache in menu is not translated.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#420]

**Comment by vasilisp** [comment]
We can put a `[%i18n ...]` around it. But how is it called in french? Wikipedia suggests antémémoire, but it is called cache most of the time, no?

Also, what about "tips"?

**Comment by Drup** [comment]
"antémémoire" ? That's adorable. :D 

Yeah, "cache" will work just fine.
As for tips, there are [several possible translations](http://www.wordreference.com/enfr/tips) but in this case, simply "aide" ?
