### ISSUE TITLE
Imagemagick still needed?

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigen-start#434]
I just tried to install ocsigen-start dependencies on a new switch (with `opam install --deps-only ocsigen-start`) and `imagemagick 0.34.1` is installed. Why?
Is it because `imagemagick` is in depext?

**Comment by vasilisp** [comment]
No, OPAM doesn't try to install any OCaml packages based on the depexts.

Bizarre. Are you sure you are working in the new switch (`opam config env --switch myswitch`) and you have installed 1.0 (and not 0.99, which is still available)?

**Comment by dannywillems** [comment]
@vasilisp Oh... I forgot `opam update` since 1.0 release... It's ok...
