### ISSUE TITLE
delete ocsigen-start 0.99

### ISSUE THREAD

**Issue by pwbs** [ocsigen/ocsigen-start#455]
I suggest we delete the existence of 0.99 
https://opam.ocaml.org/packages/ocsigen-start/ocsigen-start.0.99/

Reason: I suspect that the dependencies are broken. Earlier, someone was trying to install ocsigen-start with opam, and had ocaml 4.02, and it failed because of a dependency to package  js_of_ocaml.ppx

**Comment by pwbs** [comment]
I opened a PR on opam-repository: https://github.com/ocaml/opam-repository/pull/9179

**Comment by dannywillems** [comment]
I close as the PR on OPAM has been merged.
