### ISSUE TITLE
site created with directions from tutorial does not work

### ISSUE THREAD

**Issue by j-m-hoffmann** [ocsigen/ocsigen-start#521]
ubuntu 18.04 / eliom 6.3.0 / ocaml 4.06.1

after following this: http://ocsigen.org/tuto/6.2/manual/start
i got a site which did not respond to any clicks at all

firefox gives me this error:

TypeError: s.charCodeAt is not a function[Learn More] ocs_bc6e48a8119c523546b0373d0e1fac03.js:3280:21
read32u
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:3280:21
caml_unwrap_value_from_string</<
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:3323:19
caml_call3
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:5129:28
unwrap
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:80542:15
unwrap_js
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:80551:34
_dQs_
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:86720:36
caml_call1
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:5125:28
case$1
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:53314:48
caml_call3
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:5129:28
get_request_data
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:86722:14
init$11
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:94652:19
<anonymous>
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:111309:5
<anonymous>
http://localhost:8080/ocs_bc6e48a8119c523546b0373d0e1fac03.js:2:2

chromium gives me additionally:

Failed to load resource: the server responded with a status of 404 (Not Found) :8080/favicon.ico:1

**Comment by FlorentHoareau** [comment]
Got the very same error, see screenshot.

Additionally, firefox give this error: **"Could not load the source for blob:http://localhost:8080/c1a79847-f096-4453-845d-50ea9df46621"**. And effectively, such a file cannot be loaded. Is there an issue in the URL of some resource that the page tries to load ?

For information, the page only loads http://localhost:8080/myapp_0b735fc401f3d15620565488507bd66d.js 

![image](https://user-images.githubusercontent.com/11494303/48799471-8105e000-ed07-11e8-9cf8-c2ecd7cffb1a.png)

**Comment by FlorentHoareau** [comment]
Apparently this has to do with https://github.com/ocsigen/eliom/pull/557/commits/4562016c84c811f71a1d47ca4b2dd5128cc16b5c but opam does not seem to provide the latest version of eliom...

**Comment by vouillon** [comment]
We have made a new release of Eliom, so that should be fixed now.
