### ISSUE TITLE
Postgresql setup requirements?

### ISSUE THREAD

**Issue by RogerTarani** [ocsigen/ocsigen-start#523]
Can you pls. give the detailed requirements, especially about the DB setup to **really** get up and running in 5 mn?
That seems one cause for issues when trying to play with ocsigen start as discussed here and there (in addition to multiple dependencies requirements).
For instance, if there are multiple versions of Postgresql installed, `pg_ctl` is often not available (always? I'm not a DB expert). And `pg_ctlcluster` is generally available (from postgresql-common).
Maybe you could test the setup and fire the `make db-init` command in the real context?

PS: the messages from make commands are very dense with not really space. This could be scarring, especially. Could you make them more calm and meaningful?

**Comment by RogerTarani** [comment]
EDIT
There is no problem with pg_ctl as it is wrapped by Debian [pg_ctl_replacement](https://wiki.debian.org/PostgreSql#pg_ctl_replacement)

In fact, in my context, Make.db generates an incorrect path for the pg_ctl command:
```
$ psql --version | cut -d' ' -f 3 | cut -d'.' -f 1-2
11.1
$ echo /usr/lib/postgresql/11/bin/pg_ctl
```
I didn't have that trouble with postgres 9.6...

I could fix that with the following modification of Make.db:
`PSQL_VERSION := $(shell psql --version | cut -d' ' -f 3 | cut -d'.' -f 1)`
**It's just a workaround and must not considered as a final solution** (anyway,  any `eliom-distillery` command will generate a new Make.db file)

Is it Ocsigen that implements an incorrect rule?
Or postgresql that is messy with it's installation path [https://www.postgresql.org/support/versioning/](https://www.postgresql.org/support/versioning/)?

@balat:
As my context (Debian Strech Postgresql 11.1) is quite common, I find it important to inform/warn you about that. Ocsigen seems solidly founded (while web stuff is usually messy, and error-prone: just one missing character or with bad encoding is enough to get a website down). 
You have been improving Ocsigen for a few years to make it more and more easy to use.
But could you also consider make the messages from make commands more user-friendly? (that's a bunch of unreadable text)
And especially provide detailed requirements for getting an ocsigen website quickly up and running?
Thanks 

```
$ cat Make.db

# Rule to get the pg_ctl binary.
ifeq ($(shell psql --version 2> /dev/null),)
$(error "PostgreSQL is not installed")
else
PSQL_VERSION := $(shell psql --version | cut -d' ' -f 3 | cut -d'.' -f 1-2)
pg_ctl       := $(shell \
                  sh -c "which pg_ctl" || \
                  sh -c "echo /usr/lib/postgresql/$(PSQL_VERSION)/bin/pg_ctl")
#  PSQL_VERSION is 11.1 for postgresql 11.1 while  path is /usr/lib/postgresql/11/bin/pg_ctl
endif
```

**Comment by balat** [comment]
Thank you again for your comments. The Debian `pg_ctl` is very weak indeed and should be reworked.
I don't know the current situation with Debian right now but we'll try to explore.

**Comment by vouillon** [comment]
What about this?
```shell
pg_ctl       = $(shell which pg_ctl || \
                       ls /usr/lib/postgresql/*/bin/pg_ctl | \
                       sort -nr -t / -k 5 | head -n 1)
```

**Comment by RogerTarani** [comment]
It worked for me:
```
$ which pg_ctl
(Nothing)

$ ls /usr/lib/postgresql/*/bin/pg_ctl
/usr/lib/postgresql/11/bin/pg_ctl  /usr/lib/postgresql/9.4/bin/pg_ctl

$ ls /usr/lib/postgresql/*/bin/pg_ctl | sort -nr -t / -k 5 | head -n 1
/usr/lib/postgresql/11/bin/pg_ctl
```
I'm not a bash expert so I can just say that this script selects the more recent version of installed postgresql (implicitely, if you don't look at the sort and head parameters). 
However the previous script doesn't even see the installed postgresql 9.4 .
