### ISSUE TITLE
sudo make install fails with a strange behavior

### ISSUE THREAD

**Issue by RogerTarani** [ocsigen/ocsigen-start#527]
ocsigen-start.1.0.0

In short, all is fine until web server launched with `make test.byte` included.
Then `make all` spits  some messages with no error except `/bin/sh: 2: sassc: not found` (`make test.byte` generates th e same error message without being prevented to start correctly).
It seems that `make all` doesn't break anything because it's possible to launch the server again with `make test.byte`.

But `sudo make install.byte` fails : it tries to copy ressources from an opam repository related to root that obviously does not exist because opam is installed in non root home directory .

In addition, it seems that this creates some problem with the DB (I had to kill a postgresql process to be able to do a sequence that works (db-init; db-create; db-schema) ; not 100% sure that it's the only reason, more details next time)

Did I miss something? Especially about the user issue with opam (current user, root).
First, how can I check that `make all` does its job as expected?

Same problem with ocsigen-start.1.2.0 (in addition `make test.byte` works but not `make test.opt`  )
Same problem with ocsigen-start.1.3.0 (pinned to #master).

```
$ sudo make install
[WARNING] Running as root is not recommended
[ERROR] Variable share not found
[WARNING] Running as root is not recommended
[ERROR] Variable lib not found
make: ocamlfind: Command not found
install -d /usr/local/lib/web3
install local/lib/web3/web3.cma /usr/local/lib/web3
cp /ocsigen-toolkit/css/ot_buttons.css /ocsigen-toolkit/css/ot_carousel.css /ocsigen-toolkit/css/ot_sticky.css /ocsigen-toolkit/css/ot_datetime.css /ocsigen-toolkit/css/ot_drawer.css /ocsigen-toolkit/css/ot_icons.css /ocsigen-toolkit/css/ot_picture_uploader.css /ocsigen-toolkit/css/ot_popup.css /ocsigen-toolkit/css/ot_spinner.css static/css
cp: cannot stat ‘/ocsigen-toolkit/css/ot_buttons.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_carousel.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_sticky.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_datetime.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_drawer.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_icons.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_picture_uploader.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_popup.css’: No such file or directory
cp: cannot stat ‘/ocsigen-toolkit/css/ot_spinner.css’: No such file or directory
Makefile.style:104: recipe for target 'import-external-css' failed
make: *** [import-external-css] Error 1
```

**Comment by RogerTarani** [comment]
EDIT 
In my (ordinary) context, the trouble with `make install` is due to SHAREDIR defined in Makefile.options that looks for an `/home/root/~.opam directory` :
```
# The OPAM share directory.
SHAREDIR              := $(shell $(OPAM) config var share)

# The ocsigen-toolkit directory containing CSS files.
SHAREDIR_OT_CSS       := $(SHAREDIR)/ocsigen-toolkit/css
```
The following hard coded path works.
```
SHAREDIR              := "/home/dev/.opam/4.04.2/share"
```
Then it fails because it tries to call ocamlfind as well as ocsigenserver that are not visible for root (no ~/.opam).
```
$ sudo make run.byte
[WARNING] Running as root is not recommended
[ERROR] Variable lib not found
make: ocamlfind: Command not found
==== The website is available at http://localhost:80 ====
ocsigenserver "-v" -c /usr/local/etc/web3/web3.conf
/bin/sh: 1: ocsigenserver: not found
Makefile.os:131: recipe for target 'run.byte' failed
make: *** [run.byte] Error 127
```
What is the required opam setup?
How do you make root able to use commands that are in `~/.opam` ?

**Comment by jrochel** [comment]
Do these problems persist with current versions of ocsigen-start? (Frankly I don't see a good reason to spend time debugging ancient package versions.) You shouldn't be developing as root. Does the problem occur when trying as non-root user?

**Comment by RogerTarani** [comment]
I was not yet up and running with ocsigen-start 1.3 when I opened this issue with 1.0.
I agree. There is no need to woks as root. Using sudo as a normal user is fine for `make install `and `run`.
I had the same problem with the `sudo make` commands with ocsigen-start.1.3.0 until I could pass the right environment variables.
