### ISSUE TITLE
Prefix table names

### ISSUE THREAD

**Issue by pwbs** [ocsigen/ocsigen-start#53]
I'd like EBA to use a prefix for all tables created by EBA, to make it easier to know which are created by EBA and which are not.

**Comment by sagotch** [comment]
Even better #54. Otherwise, prefixing with eba would be a great start.

**Comment by balat** [comment]
Let's start with this (prefixing with Os_). We'll find a better solution later.

**Comment by dannywillems** [comment]
Do I need to do it? @balat

**Comment by dannywillems** [comment]
See #138

**Comment by dannywillems** [comment]
Ok, done. I close this PR.
