### ISSUE TITLE
CSS inclusion order matters

### ISSUE THREAD

**Issue by sagotch** [ocsigen/ocsigen-start#56]
Current way to include css is buggy, since rule definition override rules defined earlier.

Manually defining sheets order in the only way to go.

**Comment by dannywillems** [comment]
@sagotch Is it resolved?

**Comment by sagotch** [comment]
The old way to include css file no longer exist. As we are back to manual definition of order of sheets, I close the issue.

Code involved was:
```
let%server include_files_from dir =
  let css_files = Sys.readdir dir in
  Array.to_list @@ Array.map (fun x -> [x]) css_files
```
in `PROJECT_NAME_page.eliom` file.
