### ISSUE TITLE
ocsigen-start 2.11.0 web applications don't compile with lwt.5.0.1 (or 5.0.0)

### ISSUE THREAD

**Issue by MdeLv** [ocsigen/ocsigen-start#575]
```
$ make test.byte

js_of_eliom -w +A-4-7-9-37-38-39-41-42-44-45-48 -jsopt +base/runtime.js -ppx -ppx "ocsigen-i18n-rewriter
Test09_i18n" -c -package lwt_ppx -package js_of_ocaml-ppx -package js_of_ocaml-ppx.deriving -package ppx_
deriving.std -package ocsigen-start.client -package base -g demo_carousel2.eliom                        
File "demo_carousel2.eliom", line 79, characters 6-71:                                                  
Error: This expression has type Ot_sticky.glue option Lwt.t                                             
       but an expression was expected of type unit Lwt.t                                                
       Type Ot_sticky.glue option is not compatible with type unit                                      
make: *** [Makefile.os:284: _client/demo_carousel2.cmo] Error 2                                         
```

However, pinning lwt to 4.5.0 fixes that problem (the webapp compiles and is correctly launched).

This type mismatch seems to be related to lwt or related rewriter packages.

To fix that, can you help identify the cause?

Setup: 
ocaml-base-compiler.4.07.1
ocsigen-start.2.11.0
(ocaml, depext and ocsigen-start installed with opam)

**Comment by facelesspanda** [comment]
2.12 templates are compatible, if you want lwt5

**Comment by MdeLv** [comment]
The server that was affected is now a running with ocsigen-start.2.12.0

I can see that `template.distillery/demo_carousel2.eliom` has been changed two days ago (PR merged and ocsigen-start tagged to 2.12.0). And that it has been published today on opam, quite quickly.

It means that until today and for some unknown time, a fresh ocsigen-start setup could have been broken.

I can also see that my different ocsigen-start servers have different package sets while there are supposed to have the same as soon as they have the same ocsigen-start version (with all dependencies to their latest version). Even `opam update && opam upgrade` seems not to always upgrade all packages the same way.

I think that this is because the ocsigen-start opam file does not constrain enough the set of required packages including all dependencies.
It may also be caused by opam itself.
Do you know how to avoid that situation, at least with ocsigen-start ?

**Comment by facelesspanda** [comment]
add a `lwt < 5` constraint to ocsigen-start versions and templates preceding 2.12 I suppose.

**Comment by MdeLv** [comment]
`opam add pin lwt 4.5.0` does simply the job.
Do you know how to set with an opam command, says, a `lwt < 5` constraint? (without manually modifying the ocsigen-start opam file).

I'm still thinking that there is a problem with "opam and ocsigen-start" if it's not possible to get the same set of packages from a same version of ocsigen-start.

And I still don't understand why ocsigen-start.2.11.0 **on opam** could have been broken until yesterday 2.12.0 release. The Ocsigen team should be able to answer, if they want beginners not to be scared with dissuasive package installation.
