### ISSUE TITLE
conf-dbm apparent upstream changes trigger useless ocsigen-start main packages recompilation

### ISSUE THREAD

**Issue by MdeLv** [ocsigen/ocsigen-start#576]
```
$opam update 
$opam upgrade 
The following actions will be performed:
  ↻ recompile conf-dbm        1.0.0  [upstream changes]
  ↻ recompile dbm             1.2    [uses conf-dbm]
  ↻ recompile ocsigenserver   2.16.0 [uses dbm]
  ↻ recompile eliom           6.9.3  [uses dbm]
  ↻ recompile ocsigen-toolkit 2.4.1  [uses eliom]
  ↻ recompile ocsigen-start   2.12.0 [uses eliom]
===== ↻ 6 =====
Do you want to continue? [Y/n] n
```
However, conf-dbm.1.0.0 is already installed. 
This can be reproduced endlessly.

Is it just that conf-dbm is wrongly seen as changed? 
And why? (ocsigen-start configuration files problem or opam problem?)

**Comment by MdeLv** [comment]
See [conf-dbm triggers false "upstream changes" #16308 ](//github.com/ocaml/opam-repository/issues/16308)

**Comment by jrochel** [comment]
This should no longer be an issue, as ocsipersist has been outsourced to its own repository with its own set of packages (https://github.com/ocsigen/ocsipersist/). Ocsigen-start no longer has dependencies to database packages.
If the problem persists at all it will now be limited to users of the ocsipersist-dbm backend.

**Comment by MdeLv** [comment]
This already disappeared according to my experience.
Do you consider pgocaml and pgocaml_ppx to not be database packages on which ocsigen-start depends?

**Comment by jrochel** [comment]
Oh sorry, the version without a (direct) dependency on DB packages has not yet been published. Here it is: https://github.com/ocaml/opam-repository/pull/20111
