### ISSUE TITLE
webapp compilation problem with ocsigen-start.2.15.0 (opam installation)

### ISSUE THREAD

**Issue by MdeLv** [ocsigen/ocsigen-start#580]
Via opam, packages are correctly installed but application compilation fails: 
```
$opam update && opam upgrade
↗ upgrade   ocsigen-start      2.13.0 to 2.15.0

File "test_mobile.eliom", line 26, characters 4-47:
Error: This expression has type string -> unit Lwt.t
       but an expression was expected of type
         Deriving_Json.Json_unit.a -> 'a Lwt.t
       Type string is not compatible with type
         Deriving_Json.Json_unit.a = unit
make: *** [Makefile.os:213: _server/test_mobile.type_mli] Error 2
```

Workaround (downgrade to 2.13.0):
```
$opam pin add ocsigen-start 2.13.0
ocsigen-start is now pinned to version 2.13.0
```

Workaround (ocsigen-start.2.15.0 with eliom.6.10.1): package installation fails:
`$opam pin add eliom https://github.com/ocsigen/eliom.git#6.10.1`
but...
#=== ERROR while compiling ocsigen-toolkit.2.4.1 ==============================#

Pinning to ocsigen-start master (for including last commits) and to eliom 6.10.1, packages are correctly installed but application compilation fails:
```
$opam pin add ocsigen-start https://github.com/ocsigen/ocsigen-start.git#master
$opam pin add eliom https://github.com/ocsigen/eliom.git#6.10.1

File "test25_mobile.eliom", line 26, characters 4-47:
Error: This expression has type string -> unit Lwt.t
       but an expression was expected of type
         Deriving_Json.Json_unit.a -> 'a Lwt.t
       Type string is not compatible with type
         Deriving_Json.Json_unit.a = unit 
make: *** [Makefile.os:213: _server/test25_mobile.type_mli] Error 2
```
How is it possible to safely upgrade to last ocsigen-start version?

**Comment by vouillon** [comment]
Indeed, in file `test25_mobile.eliom` on line 25, `[%derive.json: unit]` should be replaced by `[%derive.json: string]`.
This is fixed on master, and we are in the process of making a new release with the fix.

**Comment by MdeLv** [comment]
The web app now compiles (with 2.15.0) when using  `[%derive.json: string]`
Thanks for the fix.

And the new release also compiles (package installation and web app) when pinning ocsigen-start and eliom packages as follows:
```
$ opam list --pinned
eliom         6.10.1 pinned to version 6.10.1 at git+https://github.com/ocsigen/eliom.git#6.10.1
ocsigen-start 2.16.0 pinned to version 2.16.0 at git+https://github.com/ocsigen/ocsigen-start.git#master
```

BTW
How could you manage ocsigen packages and dependencies (and related opam files) in such a way that the available ocsigen-start package(s) (and dependencies) in the opam repository are always in the correct/operational  state?
ocsigen-start installation via opam is very frequently broken because the opam repository is partially in sync with the github repo (assuming the ocsigen-start packages on github are operational).

https://github.com/ocsigen/ocsigen-start/blob/master/opam says:
  "ocaml" {>= "4.06.1"}
but until ocsigen-start.2.13.0, I could only install it on ocaml 4.07.1 as a result of the computed versions for dependencies.
What do you think about updating this opam file to clearly claim which ocaml versions actually work with ocsigen-start? (many beginners fail to install ocsigen-start because they read `ocaml >=4.06.1` on [https://opam.ocaml.org/packages/ocsigen-start/ocsigen-start.2.15.1/](https://opam.ocaml.org/packages/ocsigen-start/ocsigen-start.2.15.1/) while they have a recent ocaml compiler version (say 4.09.0). 
This opam file should constrain Ocaml compiler version as follows:
`ocaml     >=4.06.1 & <=4.07.1`

PS: Today, what is the more recent OCaml version supported by ocsigen-start (package and ALL dependencies)?

Thanks

**Comment by MdeLv** [comment]
I've just tried to install ocsigen-start.2.16.0 via opam as a beginner without any pinning tweak, as ocsigen-start.2.16.0 and eliom.6.10.1 are now both available in the opam repo (for about a few hours).
Ok.
Thanks.

How is it possible to view the ongoing publishing process of a package in the opam repo?
