### ISSUE TITLE
Unbound module Lwt_js_events when Generating the mobile application from template os.pgocaml

### ISSUE THREAD

**Issue by Random-process** [ocsigen/ocsigen-start#581]
Hello,

Executing:
> make chcp
Generate:
> File "mobile/eliom_loader.ml", line 188, characters 14-34:
> 188 | let%lwt _ = Lwt_js_events.onload () in
> 
> Errror: Unbound module Lwt_js_events

Is there a package to include in the Makefile.options ?
Or a specific module to add ?

Commenting the line allow the full build of the mobile application.

Thanks,

**Comment by ilankri** [comment]
Hello @Random-process,

> Is there a package to include in the Makefile.options ?
> Or a specific module to add ?

No, it is just a missing module prefix on the faulty line: it is `Js_of_ocaml_lwt.Lwt_js_events` and not `Lwt_js_events`.

Thanks for the report!  There is a pull request to fix this issue.
