### ISSUE TITLE
Can't build on ARM64 RockPro64 SoC - pg_ctl: command not found

### ISSUE THREAD

**Issue by olleharstedt** [ocsigen/ocsigen-start#593]
Running

`make db-init`

returns

```
make: /usr/lib/postgresql/10.12/bin/pg_ctl: Command not found
Makefile.db:101: recipe for target 'db-init' failed
make: *** [db-init] Error 127
```

Maybe `pg_ctlcluster` is meant instead? I can give more information about my system on request.

**Comment by olleharstedt** [comment]
Running `locate pg_ctl` gives

```
/etc/alternatives/pg_ctl.1.gz
/etc/postgresql/10/main/pg_ctl.conf
/usr/bin/pg_ctlcluster
/usr/lib/postgresql/10/bin/pg_ctl
/usr/share/man/man1/pg_ctl.1.gz
/usr/share/man/man1/pg_ctlcluster.1.gz
/usr/share/postgresql-common/t/085_pg_ctl.conf.t
/usr/share/postgresql/10/man/man1/pg_ctl.1.gz
```

**Comment by MdeLv** [comment]
debian 10, postgresql 11.7:
`$ which pg_ctl || ls /usr/lib/postgresql/*/bin/pg_ctl | sort -nr -t / -k 5 | head -n 1
/usr/lib/postgresql/11/bin/pg_ctl
`
Your make command is:
`/usr/lib/postgresql/10.12/bin/pg_ctl`
while pg_ctl is there:
`/usr/lib/postgresql/10/bin/pg_ctl`
hence the trouble.

Which version of ocsigen-start are you using?
What is the result of the aforementioned which command?

**Comment by olleharstedt** [comment]
Sorry, the lack of websocket support makes Ocsigen not suitable for my use-case, so I will not continue debugging. Thanks for the feedback, though.

**Comment by MdeLv** [comment]
There are modules in ocsigen (Eliom, Js_of_ocaml, Lwt) to handle symmetric communications (in addition to  automatic asymmetric communications - which saves bandwith).

I can see https://ocsigen.org/js_of_ocaml/3.1.0/api/WebSockets and other Lwt stuff.
I let the ocsigen team, which is more qualified than me on that websocket subject, brings you specific information.

My experience is that there is a lot of stuff in the ocsigen framework that needs sometime to dig a little bit and ask support.


Can you elaborate a little bit about your use case?

**Comment by olleharstedt** [comment]
My use-case is a text based game engine, sort of. I'd like websockets for OCaml in both server and client side. Right now I'm using an old lib, lwt-websockets, and trying out js_of_ocaml separately from ocsigen.

**Comment by MdeLv** [comment]
As if the issue is closed it will probably not be seen.

There are of ocsigen modules related to socket/symmetric communications
Maybe @Drup can recommend the right way how to do symmetric communications with ocsigen libraries?
- which modules to use (and which one are really deprecated, which one are old but can be used)
- how to combine asymmetric and symmetric communications (because there is no silver bullet)
- and maybe also nice ocsigen tricks 

Thanks.

**Comment by olleharstedt** [comment]
I wouldn't ping Drup unless necessary, haha. He knows who I am already.
