### ISSUE TITLE
no ocsigenserver.ext.ocsipersist-pgsql

### ISSUE THREAD

**Issue by MarkoSchuetz** [ocsigen/ocsigen-start#638]
It seems that ocsipersist is now a separate package. In the example `myapp` I had to edit the `myapp.conf.in` to use `ocsipersist.pgsql`

**Comment by jrochel** [comment]
Ocsipersist has indeed been outsourced into a bundle of libraries. I thought to have made sure that eliom-distillery creates a file myapp.conf.in that correctly loads ocsipersist-pgsql. Did you encounter the problem after upgrading eliom/ocsigen-start and then running an application generated by an older version of eliom/ocsigen-start?

**Comment by MarkoSchuetz** [comment]
I thought I might have versioning issues, so I created a new switch and installed only 4.13.1, ocsigen-start, and did an `opam depext`. I had not regenerated the `myapp` example application, but have verified this now creating `myappnew` and there is still a reference to `ocsigenserver.ext.ocsipersist-pgsql` in `myappnew.conf.in`.

**Comment by jrochel** [comment]
Which are your versions of ocsigenserver, eliom, and ocsigen-start?

**Comment by jrochel** [comment]
I found the problem: versions 4.1.0, 4.3.0, 4.4.0 (the latest published version) of ocsigen-start are incompatible with eliom < 9.0.0.
I have made a pull request to release a new version of ocsigen-start (https://github.com/ocaml/opam-repository/pull/20111) which will be available soon (by tomorrow probably).

**Comment by jrochel** [comment]
In the meantime you can pin ocsigen-start to git@github.com:ocsigen/ocsigen-start.git#4.5.0 or edit your configuration file as you've done.
Thanks for the bug report!

**Comment by MarkoSchuetz** [comment]
Thanks for the quick reaction.
