### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by 3xtraterrestrial** [ocsigen/ocsigen-start#682]
Running the steps to build Here >> 
https://github.com/ocsigen/ocsigen-start/blob/master/template.distillery/README.md

I am able to get through through with utilizing gmake and and additionally adding "postgresql-contrib" to the system, but when getting to the last step out of here 

gmake db-init
gmake db-create
gmake db-schema
gmake test.byte (or test.opt)   <<< This one >>>

I am not to sure what the issue is other than possibly format of the make files not formatted for BSD system. Or the "gmake test.opt OR test.byte" is defaulting to make and not gmake ?

make[1]: "/somepath/Makefile.db" line 36: Invalid line type
make[1]: "/somepath//Makefile.db" line 37: Invalid line type
make[1]: "/somepath/Makefile.db" line 38: Invalid line type
make[1]: "/somepath/Makefile.db" line 42: Invalid line type
make[1]: "/somepath/Makefile.db" line 97: Invalid line type
make[1]: "/somepath/Makefile.db" line 123: Invalid line type
make[1]: "/somepath/Makefile.db" line 126: warning: duplicate script for target "db-start" ignored
make[1]: "Makefile.db" line 105: warning: using previous script for "db-start" defined here
make[1]: "/somepath/Makefile.db" line 129: warning: duplicate script for target "db-status" ignored
make[1]: "Makefile.db" line 111: warning: using previous script for "db-status" defined here
make[1]: "/somepath/Makefile.db" line 132: warning: duplicate script for target "db-stop" ignored
make[1]: "/somepath/Makefile.db" line 108: warning: using previous script for "db-stop" defined here
make[1]: "/somepath/Makefile.db" line 134: Invalid line type
make[1]: "/somepath/Makefile.style" line 9: Invalid line type
make[1]: "/somepath/Makefile.style" line 11: Invalid line type
make[1]: "/somepath/Makefile.style" line 13: Invalid line type
make[1]: "/somepath/Makefile.style" line 17: Invalid line type
make[1]: "/somepath/Makefile.style" line 21: Invalid line type
make[1]: "/somepath/Makefile.style" line 22: Invalid line type
make[1]: "/somepath/Makefile.style" line 24: Invalid line type
make[1]: "/somepath/Makefile.style" line 25: Invalid line type
make[1]: "/somepath/Makefile.style" line 27: Invalid line type
make[1]: "/somepath/Makefile.style" line 31: Invalid line type
make[1]: "/somepath/Makefile.style" line 32: Invalid line type
make[1]: "/somepath/Makefile.style" line 33: Invalid line type
make[1]: "/somepath/Makefile.style" line 34: Invalid line type
make[1]: "/somepath/Makefile.style" line 35: Invalid line type
make[1]: "/somepath/Makefile.style" line 36: Invalid line type
make[1]: "/somepath/Makefile.style" line 37: Invalid line type
make[1]: "/somepath/Makefile.style" line 39: Invalid line type
make[1]: "/somepath/Makefile.style" line 53: Invalid line type
make[1]: "/somepath/Makefile.style" line 58: Invalid line type
make[1]: "/somepath/Makefile.style" line 69: Invalid line type
make[1]: "/somepath/Makefile.style" line 70: Invalid line type
make[1]: "/somepath/Makefile.style" line 73: Invalid line type
make[1]: "/somepath/Makefile.style" line 76: Invalid line type
make[1]: "/somepath/Makefile.style" line 78: Invalid line type
make[1]: "/somepath/Makefile.style" line 80: Invalid line type
make[1]: "/somepath/Makefile.style" line 112: Invalid line type
make[1]: "/somepath/Makefile.style" line 114: Invalid line type
make[1]: "/somepath/Makefile.os" line 19: Invalid line type
make[1]: "/somepath/Makefile.os" line 21: Invalid line type
make[1]: "/somepath/Makefile.os" line 130: Invalid line type
make[1]: "/somepath/Makefile.os" line 132: Invalid line type
make[1]: "/somepath/Makefile.os" line 134: Invalid line type
make[1]: "/somepath/Makefile.os" line 139: Invalid line type
make[1]: "/somepath/Makefile.os" line 141: Invalid line type
make[1]: "/somepath/Makefile.os" line 143: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 12: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 16: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 17: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 18: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 19: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 24: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 26: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 30: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 31: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 32: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 33: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 38: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 40: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 43: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 45: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 47: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 50: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 52: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 57: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 60: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 61: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 62: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 63: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 65: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 78: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 79: warning: duplicate script for target "ifeq" ignored
make[1]: "Makefile.style" line 71: warning: using previous script for "ifeq" defined here
make[1]: "/somepath/Makefile.mobile" line 79: warning: duplicate script for target "(,)" ignored
make[1]: "/somepath/Makefile.style" line 71: warning: using previous script for "(,)" defined here
make[1]: "/somepath/Makefile.mobile" line 80: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 81: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 82: warning: duplicate script for target "ifeq" ignored
make[1]: "/somepath/Makefile.style" line 71: warning: using previous script for "ifeq" defined here
make[1]: "/somepath/Makefile.mobile" line 82: warning: duplicate script for target "(,)" ignored
make[1]: "/somepath/Makefile.style" line 71: warning: using previous script for "(,)" defined here
make[1]: "/somepath/Makefile.mobile" line 83: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 90: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 91: warning: duplicate script for target "ifeq" ignored
make[1]: "Makefile.style" line 71: warning: using previous script for "ifeq" defined here
make[1]: "/somepath/Makefile.mobile" line 93: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 95: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 98: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 99: warning: duplicate script for target "ifeq" ignored
make[1]: "Makefile.style" line 71: warning: using previous script for "ifeq" defined here
make[1]: "/somepath/Makefile.mobile" line 99: warning: duplicate script for target "(,yes)" ignored
make[1]: "Makefile.mobile" line 91: warning: using previous script for "(,yes)" defined here
make[1]: "/somepath/Makefile.mobile" line 101: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 103: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 118: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 121: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 124: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 137: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 138: warning: duplicate script for target "ifeq" ignored
make[1]: "Makefile.style" line 71: warning: using previous script for "ifeq" defined here
make[1]: "/somepath/Makefile.mobile" line 139: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 185: Unknown modifier " -f 2"
make[1]: "/somepath/Makefile.mobile" line 185: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 187: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 189: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 191: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 193: Invalid line type
make[1]: "/somepath/Makefile.mobile" line 195: Invalid line type
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /somepath/
gmake: *** [Makefile.os:176: opt] Error 1

**Comment by 3xtraterrestrial** [comment]
Figured it out. Had to change some lines in the "Makefile.os" to use gmake instead of make.

**Comment by balat** [comment]
Is there a way to fix that by default?
