### ISSUE TITLE
Rename Eba into Ocsigen Start

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#83]
- [ ] On ocsigen.org
- [ ] In the code and documentation (prefix everything with Os_)
- [ ] In tutorials
- [ ] On github

**Comment by dannywillems** [comment]
The description of the GitHub repository must also be changed:
```
Eliom Base Application: an Eliom application skeleton ready to use to build your own application with users, (pre)registration, notifications, etc.
```
```
Ocsigen-start: an Eliom application skeleton ready to use to build your own application with users, (pre)registration, notifications, etc.
```

**Comment by dannywillems** [comment]
I think there is no more Eliom-base-app (or Eba) in the template. See #117

**Comment by agarwal** [comment]
I suggest to please stop using random small acronyms. A few days ago somewhere on ocsigen.org, I saw a reference to "EBA". I had no idea what that was and spent 15 minutes google'ing and searching around ocsigen repos and ocsigen.org, until I gave up deciding it isn't worth figuring out. (I'm pleased to have finally found the answer in this thread!)

Today I was reading some tutorials and saw references to "Os_*" and again was totally confused, thinking this was about some "operating system" specific feature, which sounded very odd. So I started looking for modules with this prefix that I hadn't seen before. Finally, I realized it is about this repo "ocsigen-start", which I was not previously familiar with. Now, I found the "ocsigen-toolkit" repo whose modules are prefixed as "Ot_".

I recommend following Jane Street's style of using the full project name as the prefix, and providing a `Std` module that can be opened to get the shorter names. This solves the problem for users of a project. However, code within the project is still plagued with long module names. For that we can use `module aliases as a namespace`.

**Comment by pw374** [comment]
For what it's worth, I agree that `Ot_` and `Os_` are annoying prefixes. 
When we're used to using them, we don't see they're annoying anymore. But for newcomers, it's really bad.

**Comment by agarwal** [comment]
See my related [comment](https://github.com/ocsigen/eliom/issues/294#issuecomment-242807432) about names in eliom.

**Comment by dannywillems** [comment]
It's done. I close.
